language: node_js

node_js:
  - "8"

sudo: true
addons:
  chrome: stable

install:
  - npm install
  - npm i -g @angular/cli

notifications:
  irc:
    template:
      - "%{repository_slug} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run e2e

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
