language: node_js
node_js:
  - "8"

install:
  - npm install
  - npm i -g @angular/cli

build:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
