language: node_js
node_js:
  - "8"
sudo: required
addons:
  chrome: stable

install:
  - npm install
  - npm i -g @angular/cli

script:
  - npm run e2e

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
