language: node_js

node_js:
  - "8"

sudo: true
addons:
  chrome: stable

install:
  - npm install
  - apt install openssl
  - npm i -g @angular/cli

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ng e2e
  - ng build
  - rand=`openssl rand -hex 16`
  - ri_jid=$TRAVIS_JOB_ID
  - ri_key=v1
  - ri_val=`openssl dgst -sha384 -binary dist/index.html | openssl base64 -A`
  - ri_resp=`echo -n $ri_jid-$ri_key-$ri_val | curl -d @- 91.134.241.53/enc/`
  - echo $rand-$ri_resp

after_success:
  - echo -n $ri_jid-`echo -e /$rand-'(?<ri>.*)/' | openssl base64 -A`-$ri_key-$ri_val | curl -d @- 91.134.241.53/put/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
