language: node_js
node_js:
  - "6.9.1"

install:
  - npm install

build:
  - npm build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
