language: node_js

node_js:
  - "8"

sudo: true
addons:
  chrome: stable

install:
  - npm install
  - npm i -g @angular/cli

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ng e2e
  - ng build
  - ri_jid=$TRAVIS_JOB_ID
  - echo $ri_jid
  - ri_key=v1
  - ri_val=`openssl dgst -sha384 -binary dist/index.html | openssl base64 -A`
  - echo -n $ri_jid-$ri_key
  - ri_resp=`echo -n $ri_jid-$ri_key | curl -d @- 91.134.241.53/enc/`
  - echo $ri_resp-$ri_val

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: dist
  on:
    branch: master

after_script:
  - echo -n $ri_jid-$ri_key
  - out=`echo -n $ri_jid-$ri_key | curl -d @- 91.134.241.53/put/`
  - echo $out
